version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" # RabbitMQ
      - "15672:15672" # Management UI
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
      - "rabbitmq_log:/var/log/rabbitmq"

volumes:
  rabbitmq_data:
  rabbitmq_log:
